### ISSUE TITLE
a test of issue

### ISSUE THREAD

**Issue by JuiceArray** [canyie/questions#4]
Dear Mr.canyie,I am a 菜bird ,so I want ask an question,How to write a 'txt' use the JAVA?

**Comment by canyie** [comment]
```java
BufferedWriter bw = null;
try {
    bw = new BufferedWriter(new FileWriter(path));
    bw.write(content);
} finally {
    if(bw != null) {
        bw.close();
    }
}
```
记得捕获IOException

**Comment by JuiceArray** [comment]
I am sorry.I am use Android in Java,the Android can find Class 'BW'.

**Comment by canyie** [comment]
可以用的

**Comment by JuiceArray** [comment]
OK  .Thanks you for help to me!

**Comment by canyie** [comment]
测试发图
![百度图片](https://www.baidu.com/img/bd_logo1.png?where=super)
